openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 1.0.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /fhir/r4/{resType}/{id}:
    get:
      operationId: getFhirR4RestypeId
      parameters:
      - name: resType
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
    delete:
      operationId: deleteFhirR4RestypeId
      parameters:
      - name: resType
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
    patch:
      operationId: patchFhirR4RestypeId
      parameters:
      - name: resType
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /fhir/r4/{resType}:
    get:
      operationId: getFhirR4Restype
      parameters:
      - name: resType
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
    put:
      operationId: putFhirR4Restype
      parameters:
      - name: resType
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
    post:
      operationId: postFhirR4Restype
      parameters:
      - name: resType
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /fhir/r4/metadata:
    get:
      operationId: getFhirR4Metadata
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
components: {}
