openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 1.0.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /transform:
    post:
      operationId: postTransform
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components: {}
